---
##################
# default config #
##################
#
# Note: other profiles inherit from here on a per-section bassis (meaning,
# an entire section is replaced, if specified; deeper-level overrides not
# currently supported)

default:
  data_sources:
    fte:
      full_name:        FiveThirtyEight
      html_parser:      lxml
      http_headers:     {'User-Agent': 'Mozilla/5.0'}
      fetch_interval:   1.0
      predict_url:      https://projects.fivethirtyeight.com/<YEAR>-nfl-predictions/games/
      predict_file:     projects.fivethirtyeight.com_<YEAR>-nfl-predictions_games.html
      predict_stats:
        team:           team
        spread:         spread
        chance:         pct
        score:          int
      swami_name:       FiveThirtyEight
    pfr:
      full_name:        Pro Football Reference
      html_parser:      lxml
      http_headers:     {'User-Agent': 'Mozilla/5.0'}
      fetch_interval:   1.0
      teams_url:        https://www.pro-football-reference.com/teams/<TEAM_CODE>/
      teams_file:       www.pro-football-reference.com_teams_<TEAM_CODE>.html
      games_url:        https://www.pro-football-reference.com/years/<YEAR>/games.htm
      games_file:       www.pro-football-reference.com_years_<YEAR>_games.html
      lines_url:        https://www.pro-football-reference.com/teams/<TEAM_CODE>/<YEAR>_lines.htm
      lines_file:       www.pro-football-reference.com_teams_<TEAM_CODE>_<YEAR>_lines.html
      games_stats:
        week_num:         str
        game_day_of_week: str
        game_date:        date
        gametime:         time
        winner:           team
        game_location:    str
        loser:            team
        boxscore_word:    str
        pts_win:          int
        pts_lose:         int
        yards_win:        int
        to_win:           int
        yards_lose:       int
        to_lose:          int
      lines_stats:
        game_num:         int
        opp:              team
        vegas_line:       float
        over_under:       float
        game_result:      str
        cover:            str
        ou_result:        str
      # swami making picks based on line stats
      swami_name:       Las Vegas
  databases:
    sqlite:
      db_file:   bfp.sqlite
  teams:
    # AFC East
    BUF:
      name:      Bills
      full_name: Buffalo Bills
      conf:      AFC
      div:       AFC East
      timezone:  America/New_York
      pfr_code:  buf
      fte_names: [Bills, Buffalo]
    MIA:
      name:      Dolphins
      full_name: Miami Dolphins
      conf:      AFC
      div:       AFC East
      timezone:  America/New_York
      pfr_code:  mia
      fte_names: [Dolphins, Miami]
    NE:
      name:      Patriots
      full_name: New England Patriots
      conf:      AFC
      div:       AFC East
      timezone:  America/New_York
      pfr_code:  nwe
      fte_names: [Patriots, New England]
    NYJ:
      name:      Jets
      full_name: New York Jets
      conf:      AFC
      div:       AFC East
      timezone:  America/New_York
      pfr_code:  nyj
      fte_names: [Jets, N.Y. Jets]
    # AFC North
    BAL:
      name:      Ravens
      full_name: Baltimore Ravens
      conf:      AFC
      div:       AFC North
      timezone:  America/New_York
      pfr_code:  rav
      fte_names: [Ravens, Baltimore]
    CIN:
      name:      Bengals
      full_name: Cincinnati Bengals
      conf:      AFC
      div:       AFC North
      timezone:  America/New_York
      pfr_code:  cin
      fte_names: [Bengals, Cincinnati]
    CLE:
      name:      Browns
      full_name: Cleveland Browns
      conf:      AFC
      div:       AFC North
      timezone:  America/New_York
      pfr_code:  cle
      fte_names: [Browns, Cleveland]
    PIT:
      name:      Steelers
      full_name: Pittsburgh Steelers
      conf:      AFC
      div:       AFC North
      timezone:  America/New_York
      pfr_code:  pit
      fte_names: [Steelers, Pittsburgh]
    # AFC South
    HOU:
      name:      Texans
      full_name: Houston Texans
      conf:      AFC
      div:       AFC South
      timezone:  America/Chicago
      pfr_code:  htx
      fte_names: [Texans, Houston]
    IND:
      name:      Colts
      full_name: Indianapolis Colts
      conf:      AFC
      div:       AFC South
      timezone:  America/Indianapolis
      pfr_code:  clt
      fte_names: [Colts, Indianapolis]
    JAX:
      name:      Jaguars
      full_name: Jacksonville Jaguars
      conf:      AFC
      div:       AFC South
      timezone:  America/New_York
      pfr_code:  jax
      fte_names: [Jaguars, Jacksonville]
    TEN:
      name:      Titans
      full_name: Tennessee Titans
      conf:      AFC
      div:       AFC South
      timezone:  America/Chicago
      pfr_code:  oti
      fte_names: [Titans, Tennessee]
    # AFC West
    DEN:
      name:      Broncos
      full_name: Denver Broncos
      conf:      AFC
      div:       AFC West
      timezone:  America/Denver
      pfr_code:  den
      fte_names: [Broncos, Denver]
    KC:
      name:      Chiefs
      full_name: Kansas City Chiefs
      conf:      AFC
      div:       AFC West
      timezone:  America/Chicago
      pfr_code:  kan
      fte_names: [Chiefs, Kansas City]
    LAC:
      name:      Chargers
      full_name: Los Angeles Chargers
      conf:      AFC
      div:       AFC West
      timezone:  America/Los_Angeles
      pfr_code:  sdg
      fte_names: [Chargers, L.A. Chargers]
    LV:
      name:      Raiders
      full_name: Las Vegas Raiders
      conf:      AFC
      div:       AFC West
      timezone:  America/Los_Angeles
      pfr_code:  rai
      fte_names: [Raiders, Oakland]
    # NFC East
    DAL:
      name:      Cowboys
      full_name: Dallas Cowboys
      conf:      NFC
      div:       NFC East
      timezone:  America/Chicago
      pfr_code:  dal
      fte_names: [Cowboys, Dallas]
    NYG:
      name:      Giants
      full_name: New York Giants
      conf:      NFC
      div:       NFC East
      timezone:  America/New_York
      pfr_code:  nyg
      fte_names: [Giants, N.Y. Giants]
    PHI:
      name:      Eagles
      full_name: Philadelphia Eagles
      conf:      NFC
      div:       NFC East
      timezone:  America/New_York
      pfr_code:  phi
      fte_names: [Eagles, Philadelphia]
    WAS:
      name:      Washington
      full_name: Washington Football Team
      conf:      NFC
      div:       NFC East
      timezone:  America/New_York
      pfr_code:  was
      fte_names: [Washington]
    # NFC North
    CHI:
      name:      Bears
      full_name: Chicago Bears
      conf:      NFC
      div:       NFC North
      timezone:  America/Chicago
      pfr_code:  chi
      fte_names: [Bears, Chicago]
    DET:
      name:      Lions
      full_name: Detroit Lions
      conf:      NFC
      div:       NFC North
      timezone:  America/New_York
      pfr_code:  det
      fte_names: [Lions, Detroit]
    GB:
      name:      Packers
      full_name: Green Bay Packers
      conf:      NFC
      div:       NFC North
      timezone:  America/Chicago
      pfr_code:  gnb
      fte_names: [Packers, Green Bay]
    MIN:
      name:      Vikings
      full_name: Minnesota Vikings
      conf:      NFC
      div:       NFC North
      timezone:  America/Chicago
      pfr_code:  min
      fte_names: [Vikings, Minnesota]
    # NFC South
    ATL:
      name:      Falcons
      full_name: Atlanta Falcons
      conf:      NFC
      div:       NFC South
      timezone:  America/New_York
      pfr_code:  atl
      fte_names: [Falcons, Atlanta]
    CAR:
      name:      Panthers
      full_name: Carolina Panthers
      conf:      NFC
      div:       NFC South
      timezone:  America/New_York
      pfr_code:  car
      fte_names: [Panthers, Carolina]
    'NO':
      name:      Saints
      full_name: New Orleans Saints
      conf:      NFC
      div:       NFC South
      timezone:  America/Chicago
      pfr_code:  nor
      fte_names: [Saints, New Orleans]
    TB:
      name:      Buccaneers
      full_name: Tampa Bay Buccaneers
      conf:      NFC
      div:       NFC South
      timezone:  America/New_York
      pfr_code:  tam
      fte_names: [Buccaneers, Tampa Bay]
    # NFC West
    ARZ:
      name:      Cardinals
      full_name: Arizona Cardinals
      conf:      NFC
      div:       NFC West
      timezone:  America/Phoenix
      pfr_code:  crd
      fte_names: [Cardinals, Arizona]
    LAR:
      name:      Rams
      full_name: Los Angeles Rams
      conf:      NFC
      div:       NFC West
      timezone:  America/Los_Angeles
      pfr_code:  ram
      fte_names: [Rams, L.A. Rams]
    SEA:
      name:      Seahawks
      full_name: Seattle Seahawks
      conf:      NFC
      div:       NFC West
      timezone:  America/Los_Angeles
      pfr_code:  sea
      fte_names: [Seahawks, Seattle]
    SF:
      name:      49ers
      full_name: San Francisco 49ers
      conf:      NFC
      div:       NFC West
      timezone:  America/Los_Angeles
      pfr_code:  sfo
      fte_names: [49ers, San Francisco]
    # special record(s)
    'NONE':
      name:      'None'
      full_name: n/a
      conf:      n/a
      div:       n/a
      timezone:  n/a
